<?xml version="1.0"?>
<package format="3">
  <name>rover_description</name>
  <version>0.1.0</version>
  <description>URDF robot description for the autonomous rover</description>
  <maintainer email="k28adit@gmail.com">ROSBOT</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>robot_state_publisher</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>